/**
*
* Copyright (c) 2014 Ligoo Inc.
*
* @file bms_diagnosis_impl.h
* @brief
* @note
* @author Liwei Dong
* @date 2014-2-17
*
*/

#ifndef BMS_DIAGNOSIS_IMPL_H_
#define BMS_DIAGNOSIS_IMPL_H_

#include "bms_diagnosis.h"
#include "bms_rule_stock.h"

#define BMS_DIAGNOSIS_START_RAM_POS             10
/**
 * 相关数组定义为 INT16U, 所以这里的size是按 INT16U长度计算
 */
#define BMS_SINGLE_DIAGNOSIS_SIZE               (sizeof(HigherLevelPriorityAlarmContext)/sizeof(INT16U))
#define BMS_DIAGNOSIS_POS(offset)               (BMS_DIAGNOSIS_START_RAM_POS + (offset) * BMS_SINGLE_DIAGNOSIS_SIZE)

#define BMS_DIAG_CUR_STATE_OFFSET               0
#define BMS_DIAG_FST_ALARM_COND_OFFSET          1
#define BMS_DIAG_FST_ALARM_DLY_OFFSET           2
#define BMS_DIAG_FST_ALARM_REL_COND_OFFSET      1
#define BMS_DIAG_FST_ALARM_REL_DLY_OFFSET       3
#define BMS_DIAG_SND_ALARM_COND_OFFSET          6
#define BMS_DIAG_SND_ALARM_DLY_OFFSET           7
#define BMS_DIAG_SND_ALARM_REL_COND_OFFSET      6
#define BMS_DIAG_SND_ALARM_REL_DLY_OFFSET       8
#define BMS_DIAG_TRD_ALARM_COND_OFFSET          11
#define BMS_DIAG_TRD_ALARM_DLY_OFFSET           12
#define BMS_DIAG_TRD_ALARM_REL_COND_OFFSET      11
#define BMS_DIAG_TRD_ALARM_REL_DLY_OFFSET       13
#if BMS_FORTH_ALARM_SUPPORT
#define BMS_DIAG_FTH_ALARM_COND_OFFSET          16
#define BMS_DIAG_FTH_ALARM_DLY_OFFSET           17
#define BMS_DIAG_FTH_ALARM_REL_COND_OFFSET      16
#define BMS_DIAG_FTH_ALARM_REL_DLY_OFFSET       18
#endif

#define BMS_DIAGNOSIS_COMMUNICATION_RAM_POS     BMS_DIAGNOSIS_POS(0)
#define BMS_DIAGNOSIS_VOLT_LINE_RAM_POS         BMS_DIAGNOSIS_POS(1)
#define BMS_DIAGNOSIS_TEMP_LINE_RAM_POS         BMS_DIAGNOSIS_POS(2)
#define BMS_DIAGNOSIS_CHG_HIGH_VOLT_RAM_POS     BMS_DIAGNOSIS_POS(3)
#define BMS_DIAGNOSIS_DCHG_HIGH_VOLT_RAM_POS    BMS_DIAGNOSIS_POS(4)
#define BMS_DIAGNOSIS_CHG_LOW_VOLT_RAM_POS      BMS_DIAGNOSIS_POS(5)
#define BMS_DIAGNOSIS_DCHG_LOW_VOLT_RAM_POS     BMS_DIAGNOSIS_POS(6)
#define BMS_DIAGNOSIS_CHG_HIGH_CUR_RAM_POS      BMS_DIAGNOSIS_POS(7)
#define BMS_DIAGNOSIS_DCHG_HIGH_CUR_RAM_POS     BMS_DIAGNOSIS_POS(8)
#define BMS_DIAGNOSIS_CHG_HIGH_TEMP_RAM_POS     BMS_DIAGNOSIS_POS(9)
#define BMS_DIAGNOSIS_DCHG_HIGH_TEMP_RAM_POS    BMS_DIAGNOSIS_POS(10)
#define BMS_DIAGNOSIS_CHG_LOW_TEMP_RAM_POS      BMS_DIAGNOSIS_POS(11)
#define BMS_DIAGNOSIS_DCHG_LOW_TEMP_RAM_POS     BMS_DIAGNOSIS_POS(12)
#define BMS_DIAGNOSIS_CHG_DELTA_TEMP_RAM_POS    BMS_DIAGNOSIS_POS(13)
#define BMS_DIAGNOSIS_DCHG_DELTA_TEMP_RAM_POS   BMS_DIAGNOSIS_POS(14)
#define BMS_DIAGNOSIS_INSULATION_RAM_POS        BMS_DIAGNOSIS_POS(15)
#define BMS_DIAGNOSIS_HIGH_SOC_RAM_POS          BMS_DIAGNOSIS_POS(16)
#define BMS_DIAGNOSIS_LOW_SOC_RAM_POS           BMS_DIAGNOSIS_POS(17)
#define BMS_DIAGNOSIS_CHG_DELTA_VOLT_RAM_POS    BMS_DIAGNOSIS_POS(18)
#define BMS_DIAGNOSIS_DCHG_DELTA_VOLT_RAM_POS   BMS_DIAGNOSIS_POS(19)
#define BMS_DIAGNOSIS_CHG_HTV_RAM_POS           BMS_DIAGNOSIS_POS(20)
#define BMS_DIAGNOSIS_DCHG_HTV_RAM_POS          BMS_DIAGNOSIS_POS(21)
#define BMS_DIAGNOSIS_CHG_LTV_RAM_POS           BMS_DIAGNOSIS_POS(22)
#define BMS_DIAGNOSIS_DCHG_LTV_RAM_POS          BMS_DIAGNOSIS_POS(23)
#define BMS_DIAGNOSIS_FD_OC_RAM_POS             BMS_DIAGNOSIS_POS(24)
#define BMS_DIAGNOSIS_CHGR_AC_OUTLET_HT_RAM_POS  BMS_DIAGNOSIS_POS(25)
#define BMS_DIAGNOSIS_CHGR_DC_OUTLET_HT_RAM_POS  BMS_DIAGNOSIS_POS(26)
#define BMS_DIAGNOSIS_CHGR_AC_OUTLET_TEMP_LINE_RAM_POS  BMS_DIAGNOSIS_POS(27)
#define BMS_DIAGNOSIS_CHGR_DC_OUTLET_TEMP_LINE_RAM_POS  BMS_DIAGNOSIS_POS(28)
 
#define BMS_SET_ALARM_COND(POS, VALUE, Mask) do{ \
        INT16U v = BMS_GET_ALARM_PARA_EX(POS);\
        if(VALUE) {\
            v |= Mask;\
        }else{\
            v &= (~Mask);\
        }\
        BMS_SET_ALARM_PARA_EX(POS, v);\
    }while(0)

#define BMS_SET_ALARM_PARA(POS, VALUE)                      BMS_SET_ALARM_PARA_##POS(POS, VALUE)

#define BMS_SET_ALARM_PARA_FST_ALARM_DLY(POS, VALUE)        BMS_SET_ALARM_PARA_EX(POS, VALUE)
#define BMS_SET_ALARM_PARA_FST_ALARM_REL_DLY(POS, VALUE)    BMS_SET_ALARM_PARA_EX(POS, VALUE)
#define BMS_SET_ALARM_PARA_FST_ALARM_COND(POS, VALUE)       BMS_SET_ALARM_COND(POS, VALUE, AlarmBaseInfoMask_TriggerCond)
#define BMS_SET_ALARM_PARA_FST_ALARM_REL_COND(POS, VALUE)   BMS_SET_ALARM_COND(POS, VALUE, AlarmBaseInfoMask_ReleaseCond)

#define BMS_SET_ALARM_PARA_SND_ALARM_DLY(POS, VALUE)        BMS_SET_ALARM_PARA_EX(POS, VALUE)
#define BMS_SET_ALARM_PARA_SND_ALARM_REL_DLY(POS, VALUE)    BMS_SET_ALARM_PARA_EX(POS, VALUE)
#define BMS_SET_ALARM_PARA_SND_ALARM_COND(POS, VALUE)       BMS_SET_ALARM_COND(POS, VALUE, AlarmBaseInfoMask_TriggerCond)
#define BMS_SET_ALARM_PARA_SND_ALARM_REL_COND(POS, VALUE)   BMS_SET_ALARM_COND(POS, VALUE, AlarmBaseInfoMask_ReleaseCond)

#define BMS_SET_ALARM_PARA_TRD_ALARM_DLY(POS, VALUE)        BMS_SET_ALARM_PARA_EX(POS, VALUE)
#define BMS_SET_ALARM_PARA_TRD_ALARM_REL_DLY(POS, VALUE)    BMS_SET_ALARM_PARA_EX(POS, VALUE)
#define BMS_SET_ALARM_PARA_TRD_ALARM_COND(POS, VALUE)       BMS_SET_ALARM_COND(POS, VALUE, AlarmBaseInfoMask_TriggerCond)
#define BMS_SET_ALARM_PARA_TRD_ALARM_REL_COND(POS, VALUE)   BMS_SET_ALARM_COND(POS, VALUE, AlarmBaseInfoMask_ReleaseCond)
    
#define BMS_SET_ALARM_PARA_FTH_ALARM_DLY(POS, VALUE)        BMS_SET_ALARM_PARA_EX(POS, VALUE)
#define BMS_SET_ALARM_PARA_FTH_ALARM_REL_DLY(POS, VALUE)    BMS_SET_ALARM_PARA_EX(POS, VALUE)
#define BMS_SET_ALARM_PARA_FTH_ALARM_COND(POS, VALUE)       BMS_SET_ALARM_COND(POS, VALUE, AlarmBaseInfoMask_TriggerCond)
#define BMS_SET_ALARM_PARA_FTH_ALARM_REL_COND(POS, VALUE)   BMS_SET_ALARM_COND(POS, VALUE, AlarmBaseInfoMask_ReleaseCond)

#define BMS_GET_ALARM_PARA_EX(POS)           rule_stock_get_var(start_index + BMS_DIAG_##POS##_OFFSET)
#define BMS_SET_ALARM_PARA_EX(POS, VALUE)    rule_stock_set_var(start_index + BMS_DIAG_##POS##_OFFSET, (VALUE))

#define BMS_GET_ALARM_STATE()   rule_stock_get_var(start_index + BMS_DIAG_CUR_STATE_OFFSET)

#endif /* BMS_DIAGNOSIS_IMPL_H_ */
