
/*******************************************************************************
**         °²»ÕÁ¦¸ß                                     
**
**ÎÄ ¼þ Ãû£SSPI0.h                                       
**×÷    Õß£º
**´´½¨ÈÕÆÚ£º
**ÐÞ¸Ä¼ÇÂ¼£º

**ÎÄ¼þËµÃ÷:SD¿¨µ×²ãSPIÇý¶¯Í·ÎÄ¼þ
**°æ    ±¾:
**±¸    ×¢£º
*******************************************************************************/

/* MODULE SPI0. */
#ifndef _SPI2_H
#define _SPI2_H

/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : SPI0.H
**     Project   : S12EXQ512_ucos
**     Processor : MC9S12XEQ512CAG
**     Beantype  : Init_SPI
**     Version   : Bean 01.083, Driver 01.08, CPU db: 3.00.016
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2011-5-23, 23:49
**     Abstract  :
**          This file implements the SPI (SPI0)
**          module initialization according to the Peripheral Initialization
**          Bean settings, and defines interrupt service routines prototypes.
**          The SPI includes these distinctive features:
**          • Master mode and slave mode
**          • Bi-directional mode
**          • Slave select output
**          • Mode fault error flag with CPU interrupt capability
**          • Double-buffered data register
**          • Serial clock with programmable polarity and phase
**          • Control of SPI operation during wait mode

**     Settings  :
**          Bean name                                      : SPI0
**          Device                                         : SPI0
**          Value of Preselection                          : 0
**          Value of Selection                             : 0
**          Frequency                                      : 4 MHz
**          Mode Select                                    : Master
**          SS pin mode                                    : General Purpose I/O
**          Allocate SS pin                                : Enabled
**          SS pin                                         : PS7_SS0
**          SS pin signal                                  : 
**          Clock Polarity                                 : active-high
**          Clock Phase                                    : Second edge
**          Data shift order                               : MSB first
**          Bidirectional Mode                             : Disabled
**          Stop in Wait Mode                              : no
**          Output enable in Bidirect.                     : no
**          MISO pin                                       : PS4_MISO0
**          MISO pin signal                                : 
**          MOSI pin                                       : PS5_MOSI0
**          MOSI pin signal                                : 
**          SCK pin                                        : PS6_SCK0
**          SCK pin signal                                 : 
**          Interrupt                                      : Vspi0
**          SPI receive interrupt                          : EnDisabled
**          SPI transmit interrupt                         : Disabled
**          Interrupt Priority                             : 1

**          Call Init in CPU init. code                    : yes
**          Enable SPI system                              : no
**     Contents  :
**         Init - void SPI0_Init(void);
**
**     (c) Copyright UNIS, a.s. 1997-2008
**     UNIS, a.s.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/



extern unsigned char SPI2_SendByte(unsigned char ubData);


extern void SPI2_Init(void);
/*
** ===================================================================
**     Method      :  SPI0_Init (bean Init_SPI)
**
**     Description :
**         This method initializes registers of the SPI module
**         according to this Peripheral Initialization Bean settings.
**         Call this method in user code to initialize the module.
**         By default, the method is called by PE automatically; see
**         "Call Init method" property of the bean for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#pragma CODE_SEG DEFAULT
/* END SPI0. */
#endif /* ifndef __SPI0 */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.00 [04.12]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
